name: Reusable SAST Pipeline

on:
  workflow_call:

jobs:
  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          
      - name: Check Java Version
        run: |
              java -version
              javac -version
              echo $JAVA_HOME
              which java
      
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Debug Repository
        run: |
          echo "Repository:"
          echo $GITHUB_REPOSITORY
          pwd
          ls -la

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        continue-on-error: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true

      - name: Find SARIF file
        run: |
          SARIF_FILE=$(find . -name "*.sarif" | head -n 1)
          echo "SARIF_FILE=$SARIF_FILE" >> $GITHUB_ENV

      - name: Send SARIF to Webhook
        if: always()
        run: |
          SARIF_FILE=$(find results -name "*.sarif" | head -n 1)

          echo "SARIF file: $SARIF_FILE"

          if [ -f "$SARIF_FILE" ]; then
           curl -X POST ${{ secrets.SAST_WEBHOOK }} \
            -H "Content-Type: application/json" \
            --data-binary @"$SARIF_FILE"
          else
            echo "No SARIF file found"
          fi
